version: '3'

services:
  debian-buster-php:
    restart: always
    build:
      context: ./debian
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${SYMFONY_APP_PATH}:/var/www/symfony
    env_file:
      - .env
    container_name: swa_backend

  node:
    restart: always
    build:
      context: ./node
    working_dir: /app
    volumes:
      - ${APP_FRONT_PATH}:/app
    ports:
      - ${APP_FRONT_PORT}:4545
    env_file:
      - .env
    container_name: swa_front
