Query:
  type: object
  config:
    description: "People List Query"
    fields:
      peopleList:
        type: Peoplelist
        args:
          page:
            description: "Page to filter"
            type: "Int"
        resolve: "@=resolver('people_list', [args])"
